import type { Property } from "@/types";

/**
 * Empreendimentos. Dados separados do codigo — esta lista podera vir de um
 * CMS/painel na Fase 4 sem alterar componentes.
 *
 * Regras: sem precos fixos sem data de atualizacao (usar ressalva na UI),
 * sem imagens nao autorizadas, sem dados inventados.
 */
export const properties: Property[] = [
  {
    id: "vibra-vila-sonia",
    slug: "vibra-parque-vila-sonia",
    name: "Vibra Parque Vila Sonia",
    neighborhood: "Vila Sonia",
    city: "Sao Paulo",
    bedrooms: "1 e 2 dormitorios",
    area: "27 a 41 m2",
    priceFrom: 242100,
    delivery: "2028",
    status: "lancamento",
    description:
      "Condominio fechado a 5 minutos do Metro Vila Sonia e do Parque Chacara do Jockey, com Shopping Taboao, Butanta Shopping e Raposo Shopp a 10 minutos, Colegio Itaca a 4 minutos, Hospital Leforte a 8 minutos e UniFECAF a 7 minutos.",
    features: ["Piscina", "Academia", "Playground", "Seguranca (condominio fechado)", "Pet friendly"],
    images: [],
    featured: false,
  },
  {
    id: "vibra-estacao-vila-sonia",
    slug: "vibra-estacao-vila-sonia",
    name: "Vibra Estacao Vila Sonia",
    neighborhood: "Vila Sonia",
    city: "Sao Paulo",
    bedrooms: "1 e 2 dormitorios",
    area: "26,82 a 43,25 m2",
    priceFrom: 307800,
    delivery: "2028",
    status: "lancamento",
    description:
      "Condominio fechado a 8 minutos a pe da Estacao Vila Sonia (Linha 4-Amarela), com area de lazer completa e unidades enquadradas no Programa Minha Casa, Minha Vida.",
    features: [
      "Piscina",
      "Academia",
      "Salao de festas",
      "Salao gourmet e coworking",
      "Playground",
      "Brinquedoteca",
      "Pet care",
      "Espaco beleza",
      "Sport bar",
      "Minimercado",
    ],
    images: [
      "/properties/vibra-estacao-vila-sonia/fachada-torres.jpg",
      "/properties/vibra-estacao-vila-sonia/portaria-perspectiva-1.jpg",
      "/properties/vibra-estacao-vila-sonia/piscina.jpg",
      "/properties/vibra-estacao-vila-sonia/churrasqueira.jpg",
      "/properties/vibra-estacao-vila-sonia/salao-de-festas.jpg",
      "/properties/vibra-estacao-vila-sonia/salao-de-jogos.jpg",
      "/properties/vibra-estacao-vila-sonia/espaco-luau.jpg",
      "/properties/vibra-estacao-vila-sonia/sport-bar.jpg",
      "/properties/vibra-estacao-vila-sonia/brinquedoteca.jpg",
      "/properties/vibra-estacao-vila-sonia/playground.jpg",
      "/properties/vibra-estacao-vila-sonia/salao-gourmet-coworking-1.jpg",
      "/properties/vibra-estacao-vila-sonia/salao-gourmet-coworking-2.jpg",
      "/properties/vibra-estacao-vila-sonia/minimercado.jpg",
      "/properties/vibra-estacao-vila-sonia/espaco-beleza.jpg",
      "/properties/vibra-estacao-vila-sonia/academia.jpg",
      "/properties/vibra-estacao-vila-sonia/bicicletario.jpg",
      "/properties/vibra-estacao-vila-sonia/pet-care.jpg",
      "/properties/vibra-estacao-vila-sonia/implantacao.jpg",
      "/properties/vibra-estacao-vila-sonia/mapa-localizacao.jpg",
      "/properties/vibra-estacao-vila-sonia/foto-aerea-mobilidade.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-1-quarto.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-2-quartos-37m.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-2-quartos-41m.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-2-quartos-43m.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-detalhada-1.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-detalhada-2.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-detalhada-3.jpg",
      "/properties/vibra-estacao-vila-sonia/lifestyle-1.jpg",
      "/properties/vibra-estacao-vila-sonia/lifestyle-2.jpg",
      "/properties/vibra-estacao-vila-sonia/lifestyle-3.jpg",
      "/properties/vibra-estacao-vila-sonia/lifestyle-4.jpg",
    ],
    featured: true,
  },
  {
    id: "vibra-estacao-campo-limpo",
    slug: "vibra-estacao-campo-limpo",
    name: "Vibra Estacao Campo Limpo",
    neighborhood: "Socorro",
    city: "Sao Paulo",
    bedrooms: "1 e 2 dormitorios",
    area: "26,45 a 42,24 m2",
    priceFrom: 254900,
    delivery: "2028",
    status: "lancamento",
    description:
      "Condominio com 1 torre e 450 unidades na Estrada de Itapecerica, na regiao de Socorro/Vila Maracana, em Sao Paulo. Area de lazer com portaria com espaco para delivery, espaco para minimercado, espaco gourmet, salao de festas, churrasqueiras, solario, piscina, bicicletario, espaco luau e espaco fitness.",
    features: [
      "Piscina",
      "Espaco fitness",
      "Salao de festas",
      "Espaco gourmet",
      "Churrasqueiras",
      "Solario",
      "Bicicletario",
      "Espaco luau",
      "Minimercado",
    ],
    images: [],
    featured: false,
  },
];
