import type { Property } from "@/types";

/**
 * Empreendimentos. Dados separados do codigo — esta lista podera vir de um
 * CMS/painel na Fase 4 sem alterar componentes.
 *
 * Regras: sem precos fixos sem data de atualizacao (usar ressalva na UI),
 * sem imagens nao autorizadas, sem dados inventados.
 */
export const properties: Property[] = [
  {
    id: "vibra-vila-sonia",
    slug: "vibra-parque-vila-sonia",
    name: "Vibra Parque Vila Sônia",
    neighborhood: "Vila Sônia",
    city: "São Paulo",
    bedrooms: "1 e 2 dormitórios",
    area: "27 a 41 m2",
    priceFrom: 242100,
    priceRef: "ago/2026",
    developer: "Vibra",
    delivery: "2028",
    status: "lancamento",
    address: "Rua Caminho do Engenho, 584 - Vila Sônia, São Paulo - SP",
    nearby: [
      { place: "Metrô Vila Sônia (Linha 4-Amarela)" },
      { place: "Parque Chácara do Jockey" },
      { place: "Av. Pirajussara" },
      { place: "Colégio Ítaca" },
      { place: "Assaí e Max Atacadista" },
      { place: "5 shoppings (Raposo, Taboão, Butantã, Jd. Sul e Morumbi Town)" },
      { place: "Hospitais da região (Family, Leforte e outros)" },
      { place: "UniFECAF" },
    ],
    description:
      "Condomínio fechado de 2 torres na Rua Caminho do Engenho, na Vila Sônia, a 5 minutos de ônibus do Metrô Vila Sônia (Linha 4-Amarela) e a 5 minutos a pé do Parque Chácara do Jockey. Área de lazer completa e unidades enquadradas no Programa Minha Casa, Minha Vida.",
    features: [
      "Piscina adulto e infantil",
      "Solário",
      "Churrasqueira",
      "Playground",
      "Salão de festas",
      "Salão gourmet e coworking",
      "Salão de jogos",
      "Academia",
      "Brinquedoteca",
      "Espaço beleza",
      "Pet care",
      "Pet place",
      "Minimercado",
      "Portaria com espaço delivery",
    ],
    images: [
      "/properties/vibra-parque-vila-sonia/fachada-torres.jpg",
      "/properties/vibra-parque-vila-sonia/portaria.jpg",
      "/properties/vibra-parque-vila-sonia/piscina.jpg",
      "/properties/vibra-parque-vila-sonia/churrasqueira.jpg",
      "/properties/vibra-parque-vila-sonia/playground.jpg",
      "/properties/vibra-parque-vila-sonia/salao-de-jogos.jpg",
      "/properties/vibra-parque-vila-sonia/salao-gourmet-coworking.jpg",
      "/properties/vibra-parque-vila-sonia/academia.jpg",
      "/properties/vibra-parque-vila-sonia/salao-de-festas.jpg",
      "/properties/vibra-parque-vila-sonia/espaco-beleza.jpg",
      "/properties/vibra-parque-vila-sonia/brinquedoteca.jpg",
      "/properties/vibra-parque-vila-sonia/pet-care.jpg",
      "/properties/vibra-parque-vila-sonia/pet-place.jpg",
      "/properties/vibra-parque-vila-sonia/minimercado.jpg",
      "/properties/vibra-parque-vila-sonia/implantacao.jpg",
      "/properties/vibra-parque-vila-sonia/mapa-localizacao.jpg",
      "/properties/vibra-parque-vila-sonia/planta-1-quarto.jpg",
      "/properties/vibra-parque-vila-sonia/planta-2-quartos-34m-a.jpg",
      "/properties/vibra-parque-vila-sonia/planta-2-quartos-34m-b.jpg",
      "/properties/vibra-parque-vila-sonia/planta-2-quartos-37m.jpg",
      "/properties/vibra-parque-vila-sonia/planta-2-quartos-41m.jpg",
    ],
    featured: false,
  },
  {
    id: "vibra-estacao-vila-sonia",
    slug: "vibra-estacao-vila-sonia",
    name: "Vibra Estação Vila Sônia",
    neighborhood: "Vila Sônia",
    city: "São Paulo",
    bedrooms: "1 e 2 dormitórios",
    area: "26,82 a 43,25 m2",
    priceFrom: 307800,
    priceRef: "ago/2026",
    developer: "Vibra",
    delivery: "2028",
    status: "lancamento",
    address: "Rua Dias Vieira, 420 - Vila Sônia, São Paulo - SP",
    nearby: [
      { place: "Estação Vila Sônia (Linha 4-Amarela)" },
      { place: "Assaí Atacadista Francisco Morato" },
      { place: "Shopping Butantã" },
      { place: "Parque Villa-Lobos" },
      { place: "Shopping Eldorado" },
    ],
    description:
      "Condomínio fechado a 8 minutos a pé da Estação Vila Sônia (Linha 4-Amarela), com área de lazer completa e unidades enquadradas no Programa Minha Casa, Minha Vida.",
    features: [
      "Piscina",
      "Academia",
      "Salão de festas",
      "Salão gourmet e coworking",
      "Playground",
      "Brinquedoteca",
      "Pet care",
      "Espaço beleza",
      "Sport bar",
      "Minimercado",
    ],
    images: [
      "/properties/vibra-estacao-vila-sonia/fachada-torres.jpg",
      "/properties/vibra-estacao-vila-sonia/portaria-perspectiva-1.jpg",
      "/properties/vibra-estacao-vila-sonia/piscina.jpg",
      "/properties/vibra-estacao-vila-sonia/churrasqueira.jpg",
      "/properties/vibra-estacao-vila-sonia/salao-de-festas.jpg",
      "/properties/vibra-estacao-vila-sonia/salao-de-jogos.jpg",
      "/properties/vibra-estacao-vila-sonia/espaco-luau.jpg",
      "/properties/vibra-estacao-vila-sonia/sport-bar.jpg",
      "/properties/vibra-estacao-vila-sonia/brinquedoteca.jpg",
      "/properties/vibra-estacao-vila-sonia/playground.jpg",
      "/properties/vibra-estacao-vila-sonia/salao-gourmet-coworking-1.jpg",
      "/properties/vibra-estacao-vila-sonia/salao-gourmet-coworking-2.jpg",
      "/properties/vibra-estacao-vila-sonia/minimercado.jpg",
      "/properties/vibra-estacao-vila-sonia/espaco-beleza.jpg",
      "/properties/vibra-estacao-vila-sonia/academia.jpg",
      "/properties/vibra-estacao-vila-sonia/bicicletario.jpg",
      "/properties/vibra-estacao-vila-sonia/pet-care.jpg",
      "/properties/vibra-estacao-vila-sonia/implantacao.jpg",
      "/properties/vibra-estacao-vila-sonia/mapa-localizacao.jpg",
      "/properties/vibra-estacao-vila-sonia/foto-aerea-mobilidade.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-1-quarto.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-2-quartos-37m.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-2-quartos-41m.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-2-quartos-43m.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-detalhada-1.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-detalhada-2.jpg",
      "/properties/vibra-estacao-vila-sonia/planta-detalhada-3.jpg",
      "/properties/vibra-estacao-vila-sonia/lifestyle-1.jpg",
      "/properties/vibra-estacao-vila-sonia/lifestyle-2.jpg",
      "/properties/vibra-estacao-vila-sonia/lifestyle-3.jpg",
      "/properties/vibra-estacao-vila-sonia/lifestyle-4.jpg",
    ],
    featured: true,
  },
  {
    id: "vibra-estacao-campo-limpo",
    slug: "vibra-estacao-campo-limpo",
    name: "Vibra Estação Campo Limpo",
    neighborhood: "Campo Limpo",
    city: "São Paulo",
    bedrooms: "1 e 2 dormitórios",
    area: "26,45 a 42,24 m2",
    priceFrom: 254900,
    priceRef: "ago/2026",
    developer: "Vibra",
    delivery: "2028",
    status: "lancamento",
    address: "Estrada de Itapecerica, 2369 - Jardim Germânia/Vila Maracanã, São Paulo, SP",
    coords: { lat: -23.6506, lng: -46.756 },
    nearby: [
      { place: "Estação Campo Limpo (Linha 5-Lilás)" },
      { place: "Estação Vila das Belezas (Linha 5-Lilás)" },
      { place: "Shopping Campo Limpo" },
      { place: "Hospital Campo Limpo" },
      { place: "Sesc Campo Limpo" },
      { place: "Roldão Atacadista" },
    ],
    description:
      "Condomínio com 1 torre na Estrada de Itapecerica, na região de Campo Limpo, Zona Sul de São Paulo, próximo às Estações Campo Limpo e Vila das Belezas (Linha 5-Lilás) e ao Shopping Campo Limpo. Apartamentos de 1 e 2 quartos com opção de varanda, lazer de clube completo e unidades enquadradas no Programa Minha Casa, Minha Vida.",
    features: [
      "Piscina",
      "Churrasqueira",
      "Salão de festas",
      "Salão gourmet",
      "Salão de jogos",
      "Salão gourmet e coworking",
      "Academia",
      "Brinquedoteca",
      "Playground",
      "Espaço beleza",
      "Pet care",
      "Pet place",
      "Espaço luau",
      "Rooftop",
      "Minimercado",
    ],
    images: [
      "/properties/vibra-estacao-campo-limpo/fachada-torres.jpg",
      "/properties/vibra-estacao-campo-limpo/piscina.jpg",
      "/properties/vibra-estacao-campo-limpo/churrasqueira.jpg",
      "/properties/vibra-estacao-campo-limpo/salao-de-festas.jpg",
      "/properties/vibra-estacao-campo-limpo/salao-gourmet.jpg",
      "/properties/vibra-estacao-campo-limpo/salao-de-jogos.jpg",
      "/properties/vibra-estacao-campo-limpo/salao-gourmet-coworking.jpg",
      "/properties/vibra-estacao-campo-limpo/academia.jpg",
      "/properties/vibra-estacao-campo-limpo/brinquedoteca.jpg",
      "/properties/vibra-estacao-campo-limpo/playground.jpg",
      "/properties/vibra-estacao-campo-limpo/espaco-beleza.jpg",
      "/properties/vibra-estacao-campo-limpo/pet-care.jpg",
      "/properties/vibra-estacao-campo-limpo/pet-place.jpg",
      "/properties/vibra-estacao-campo-limpo/espaco-luau.jpg",
      "/properties/vibra-estacao-campo-limpo/rooftop.jpg",
      "/properties/vibra-estacao-campo-limpo/minimercado.jpg",
      "/properties/vibra-estacao-campo-limpo/implantacao.jpg",
      "/properties/vibra-estacao-campo-limpo/foto-aerea-mobilidade.jpg",
      "/properties/vibra-estacao-campo-limpo/mapa-localizacao.jpg",
      "/properties/vibra-estacao-campo-limpo/planta-1-quarto.jpg",
      "/properties/vibra-estacao-campo-limpo/planta-2-quartos-37m.jpg",
      "/properties/vibra-estacao-campo-limpo/planta-2-quartos-39m.jpg",
      "/properties/vibra-estacao-campo-limpo/planta-2-quartos-42m-a.jpg",
      "/properties/vibra-estacao-campo-limpo/planta-2-quartos-42m-b.jpg",
    ],
    featured: false,
  },
  {
    id: "vibra-jardim-bonfiglioli",
    slug: "vibra-jardim-bonfiglioli",
    name: "Vibra Jardim Bonfiglioli",
    neighborhood: "Jardim Bonfiglioli",
    city: "São Paulo",
    bedrooms: "2 dormitórios",
    area: "32 a 42 m2",
    priceFrom: 276000,
    priceRef: "ago/2026",
    developer: "Vibra",
    delivery: "2028",
    status: "lancamento",
    address: "Rua Azem Abdalla, 571 - Jardim Bonfiglioli, São Paulo - SP",
    nearby: [
      { place: "Estação Butantã (Linha 4-Amarela)" },
      { place: "Pinheiros" },
      { place: "Avenida Paulista" },
    ],
    description:
      "Condomínio residencial de 2 torres no Jardim Bonfiglioli, Zona Oeste de São Paulo, a 10 minutos a pé da Estação Butantã (Linha 4-Amarela) — 10 minutos de Pinheiros e 15 da Avenida Paulista. Apartamentos de 2 dormitórios com opção de varanda, area de lazer completa e unidades enquadradas no Programa Minha Casa, Minha Vida.",
    features: [
      "Piscina",
      "Solário",
      "Academia",
      "Salão de festas",
      "Salão gourmet e coworking",
      "Playground",
      "Brinquedoteca",
      "Pet care",
      "Espaço beleza",
      "Sport bar",
      "Salão de jogos",
      "Churrasqueira",
      "Minimercado",
      "Bicicletario",
    ],
    images: [
      "/properties/vibra-jardim-bonfiglioli/fachada-torres.jpg",
      "/properties/vibra-jardim-bonfiglioli/piscina.jpg",
      "/properties/vibra-jardim-bonfiglioli/churrasqueira.jpg",
      "/properties/vibra-jardim-bonfiglioli/salao-de-festas.jpg",
      "/properties/vibra-jardim-bonfiglioli/sport-bar.jpg",
      "/properties/vibra-jardim-bonfiglioli/salao-de-jogos.jpg",
      "/properties/vibra-jardim-bonfiglioli/brinquedoteca.jpg",
      "/properties/vibra-jardim-bonfiglioli/playground.jpg",
      "/properties/vibra-jardim-bonfiglioli/espaco-luau.jpg",
      "/properties/vibra-jardim-bonfiglioli/academia.jpg",
      "/properties/vibra-jardim-bonfiglioli/espaco-beleza.jpg",
      "/properties/vibra-jardim-bonfiglioli/minimercado.jpg",
      "/properties/vibra-jardim-bonfiglioli/pet-place.jpg",
      "/properties/vibra-jardim-bonfiglioli/apartamento-decorado.jpg",
      "/properties/vibra-jardim-bonfiglioli/implantacao.jpg",
      "/properties/vibra-jardim-bonfiglioli/mapa-localizacao.jpg",
      "/properties/vibra-jardim-bonfiglioli/foto-aerea-mobilidade.jpg",
      "/properties/vibra-jardim-bonfiglioli/planta-2-quartos-1.jpg",
      "/properties/vibra-jardim-bonfiglioli/planta-2-quartos-2.jpg",
      "/properties/vibra-jardim-bonfiglioli/planta-2-quartos-3.jpg",
    ],
    featured: false,
  },
];
