import type { Property } from "@/types";

/**
 * Empreendimentos EXTO do Britto (alto padrao). Dados extraidos dos livros
 * digitais oficiais da EXTO — nada de preco inventado (todos em lancamento,
 * "Sob consulta"). Imagens pendentes: aguardando material oficial da EXTO
 * (os livros sao arte full-bleed, nao rendem recorte limpo). Enderecos,
 * entregas e ficha confirmados pelo cliente/material.
 */
export const properties: Property[] = [
  // NOTA: o DESTAQUE é o primeiro `featured: true` do array (FeaturedShowcase
  // usa `.find(p => p.featured)`). Hoje o destaque é o Château Jardin Lumière.
  {
    id: "chateau-jardin-harmonie",
    slug: "chateau-jardin-harmonie",
    name: "Château Jardin Harmonie",
    neighborhood: "Cidade Jardim",
    city: "São Paulo",
    bedrooms: "4 suítes",
    area: "185 a 248 m2",
    priceLabel: "Sob consulta",
    developer: "EXTO e Tegra",
    delivery: "Abr/2029",
    status: "lancamento",
    address: "Rua Ministro Nelson Hungria, 400 - São Paulo - SP",
    specs: [
      { label: "Suítes", value: "4" },
      { label: "Fase", value: "Harmonie" },
      { label: "Arquitetura", value: "Dina Melaragno" },
      { label: "Paisagismo", value: "EDSA" },
    ],
    nearby: [
      { place: "Ponte Estaiada" },
      { place: "Ponte Morumbi" },
      { place: "Marginal Pinheiros" },
    ],
    description:
      "Château Jardin Harmonie é uma das duas fases do Château Jardin, novo marco residencial no Novo Eixo Cidade Jardim — o último grande terreno da região, entre as pontes Morumbi e Estaiada. Realização EXTO e Tegra, com arquitetura clássica reinterpretada com leveza contemporânea (Dina Melaragno) e paisagismo internacional by EDSA. Apartamentos de 4 suítes com 185, 215 e 248 m², em condomínio com lazer estilo private club.",
    features: [
      "Quadra de tênis (saibro)",
      "Quadra de padel",
      "Le Club — fitness center equipado",
      "Piscina coberta de 25m com raia",
      "Piscina descoberta e infantil",
      "Wellness spa com hidromassagem",
      "Sala de massagem",
      "Espaço beauty",
      "Salão de festas e lounges",
      "Family room",
      "Brinquedoteca",
      "Playground",
      "Pet place e banho pet",
      "Praça externa",
      "Mini market",
      "Concierge / courrier",
    ],
    images: [
      "/properties/chateau-jardin-harmonie/fachada.jpg",
      "/properties/chateau-jardin-harmonie/vista-lateral-da-fachada.jpg",
      "/properties/chateau-jardin-harmonie/portico-alto-padrao-construtivo-com-design-e.jpg",
      "/properties/chateau-jardin-harmonie/portico-alto-padrao-construtivo-com-design-e-2.jpg",
      "/properties/chateau-jardin-harmonie/lobby.jpg",
      "/properties/chateau-jardin-harmonie/lobby-1.jpg",
      "/properties/chateau-jardin-harmonie/family-room.jpg",
      "/properties/chateau-jardin-harmonie/praca-externa.jpg",
      "/properties/chateau-jardin-harmonie/praca-externa-1.jpg",
      "/properties/chateau-jardin-harmonie/quadra-de-tenis-de-saibro.jpg",
      "/properties/chateau-jardin-harmonie/club-tennis.jpg",
      "/properties/chateau-jardin-harmonie/quadra-de-padel.jpg",
      "/properties/chateau-jardin-harmonie/le-club-fitness-center-equipado.jpg",
      "/properties/chateau-jardin-harmonie/piscina-coberta-de-25m-com-raia.jpg",
      "/properties/chateau-jardin-harmonie/piscina-descoberta-piscina-infantil-deck-mol.jpg",
      "/properties/chateau-jardin-harmonie/piscina-descoberta-piscina-infantil-deck-mol-2.jpg",
      "/properties/chateau-jardin-harmonie/wellness-spa-com-hidromassagem.jpg",
      "/properties/chateau-jardin-harmonie/sala-de-massagem.jpg",
      "/properties/chateau-jardin-harmonie/espaco-beauty.jpg",
      "/properties/chateau-jardin-harmonie/salao-de-festas-e-lounges.jpg",
      "/properties/chateau-jardin-harmonie/brinquedoteca.jpg",
      "/properties/chateau-jardin-harmonie/playground.jpg",
      "/properties/chateau-jardin-harmonie/pet-place-campo-gramado.jpg",
      "/properties/chateau-jardin-harmonie/banho-pet.jpg",
      "/properties/chateau-jardin-harmonie/aerea-duas-fases.jpg",
      "/properties/chateau-jardin-harmonie/aerea-lazer.jpg",
    ],
    featured: false,
  },
  {
    id: "chateau-jardin-lumiere",
    slug: "chateau-jardin-lumiere",
    name: "Château Jardin Lumière",
    neighborhood: "Cidade Jardim",
    city: "São Paulo",
    bedrooms: "4 suítes",
    area: "355 m2",
    priceLabel: "Sob consulta",
    developer: "EXTO e Tegra",
    delivery: "Abr/2029",
    status: "lancamento",
    address: "Rua Ministro Nelson Hungria, 400 - São Paulo - SP",
    specs: [
      { label: "Suítes", value: "4" },
      { label: "Fase", value: "Lumière" },
      { label: "Vagas", value: "5 a 6 por apartamento" },
      { label: "Terreno", value: "mais de 6.100 m²" },
      { label: "Arquitetura", value: "Dina Melaragno" },
      { label: "Paisagismo", value: "EDSA" },
    ],
    nearby: [
      { place: "Ponte Estaiada" },
      { place: "Ponte Morumbi" },
      { place: "Marginal Pinheiros" },
    ],
    description:
      "Château Jardin Lumière é a fase de maior metragem do Château Jardin, no Novo Eixo Cidade Jardim — último grande terreno da região, entre as pontes Morumbi e Estaiada. Realização EXTO e Tegra, com projeto internacional (arquitetura Dina Melaragno, paisagismo by EDSA), fachada em molduras e pedra, terreno de mais de 6.100 m² e 5 a 6 vagas por apartamento. Apartamentos de 4 suítes com 355 m² e lazer estilo private club.",
    features: [
      "Quadra de tênis (saibro)",
      "Quadra de padel",
      "Fitness center equipado",
      "Piscina coberta de 25m com raia",
      "Piscina descoberta e infantil",
      "Wellness spa com hidromassagem",
      "Sala de massagem",
      "Espaço beauty",
      "Salão de festas e lounges",
      "Salão de jogos",
      "Brinquedoteca",
      "Playground",
      "Pet place e banho pet",
      "Praça externa",
      "Mini market",
      "Concierge / courrier",
    ],
    images: [
      "/properties/chateau-jardin-lumiere/fachada.jpg",
      "/properties/chateau-jardin-lumiere/fachada-com-aplicacao-de-molduras-e-textura.jpg",
      "/properties/chateau-jardin-lumiere/portico.jpg",
      "/properties/chateau-jardin-lumiere/portico-1.jpg",
      "/properties/chateau-jardin-lumiere/lobby.jpg",
      "/properties/chateau-jardin-lumiere/lobby-projeto-internacional-de-acabamentos-n.jpg",
      "/properties/chateau-jardin-lumiere/praca-externa.jpg",
      "/properties/chateau-jardin-lumiere/praca-externa-1.jpg",
      "/properties/chateau-jardin-lumiere/quadra-de-tenis-de-saibro.jpg",
      "/properties/chateau-jardin-lumiere/club-tennis.jpg",
      "/properties/chateau-jardin-lumiere/quadra-de-paddle.jpg",
      "/properties/chateau-jardin-lumiere/fitness-center-equipado.jpg",
      "/properties/chateau-jardin-lumiere/piscina-coberta-de-25m-com-raia.jpg",
      "/properties/chateau-jardin-lumiere/piscina-descoberta-piscina-infantil-deck-mol.jpg",
      "/properties/chateau-jardin-lumiere/piscina-descoberta-piscina-infantil-deck-mol-2.jpg",
      "/properties/chateau-jardin-lumiere/wellness-spa-com-hidromassagem.jpg",
      "/properties/chateau-jardin-lumiere/sala-de-massagem.jpg",
      "/properties/chateau-jardin-lumiere/espaco-beauty.jpg",
      "/properties/chateau-jardin-lumiere/salao-de-festas-e-lounges.jpg",
      "/properties/chateau-jardin-lumiere/salao-de-jogos.jpg",
      "/properties/chateau-jardin-lumiere/brinquedoteca.jpg",
      "/properties/chateau-jardin-lumiere/playground.jpg",
      "/properties/chateau-jardin-lumiere/pet-place-campo-gramado.jpg",
      "/properties/chateau-jardin-lumiere/banho-pet.jpg",
      "/properties/chateau-jardin-lumiere/vista-area-do-lazer.jpg",
      "/properties/chateau-jardin-lumiere/aerea-duas-fases.jpg",
      "/properties/chateau-jardin-lumiere/aerea-lazer.jpg",
    ],
    featured: true,
  },
  {
    id: "legacy-guedala",
    slug: "legacy-guedala",
    name: "Legacy Guedala",
    neighborhood: "Jardim Guedala",
    city: "São Paulo",
    bedrooms: "3 suítes",
    area: "140 a 173 m2",
    priceLabel: "Sob consulta",
    developer: "EXTO",
    delivery: "2027",
    status: "lancamento",
    address: "Rua Carlos Lima Morel, 115 - Jardim Guedala, São Paulo - SP",
    tourUrl: "https://tour3d.piperz.io/RJuQUvyDW2p",
    specs: [
      { label: "Suítes", value: "3" },
      { label: "Torres", value: "1 (residencial)" },
      { label: "Altura", value: "~120 m" },
      { label: "Arquitetura", value: "Dina Melaragno" },
    ],
    nearby: [
      { place: "Estação São Paulo-Morumbi (Metrô Linha 4-Amarela)" },
      { place: "Hospital Israelita Albert Einstein" },
      { place: "Av. Prof. Francisco Morato" },
      { place: "Av. Jorge João Saad" },
      { place: "Av. Morumbi" },
      { place: "Marginal Pinheiros" },
    ],
    description:
      "Legacy Guedala é o empreendimento mais alto do Jardim Guedala — uma torre puramente residencial com aproximadamente 120 metros de altura, cercada por um dos cenários mais verdes e nobres de São Paulo. Assinatura by EXTO (arquitetura de Dina Melaragno), com apartamentos de 140 m² (3 suítes / 4 dormitórios) e 173 m² (3 suítes), a 670 metros da Estação São Paulo-Morumbi do Metrô. Um marco para a região e um legado para a família.",
    features: [
      "Quadra de tênis",
      "Piscina descoberta",
      "Piscina coberta",
      "Fitness",
      "Espaço beauty",
      "Gourmet",
      "Coworking",
      "Brinquedoteca",
      "Salão de festas",
      "Pet place",
      "Mini market",
      "Serviço de personalização das unidades",
    ],
    images: [
      "/properties/legacy-guedala/fachada.jpg",
      "/properties/legacy-guedala/voo-de-passaro.jpg",
      "/properties/legacy-guedala/portico.jpg",
      "/properties/legacy-guedala/portico-2.jpg",
      "/properties/legacy-guedala/vista-lateral.jpg",
      "/properties/legacy-guedala/lobby.jpg",
      "/properties/legacy-guedala/vista-do-apartamento.jpg",
      "/properties/legacy-guedala/quadra-de-tenis.jpg",
      "/properties/legacy-guedala/piscina-descoberta.jpg",
      "/properties/legacy-guedala/piscina-coberta.jpg",
      "/properties/legacy-guedala/fitness.jpg",
      "/properties/legacy-guedala/espaco-beauty.jpg",
      "/properties/legacy-guedala/gourmet.jpg",
      "/properties/legacy-guedala/coworking.jpg",
      "/properties/legacy-guedala/brinquedoteca.jpg",
      "/properties/legacy-guedala/salao-de-festas.jpg",
      "/properties/legacy-guedala/pet.jpg",
      "/properties/legacy-guedala/mapa-localizacao.jpg",
    ],
    featured: false,
  },
  {
    id: "palm-collection-pacaembu",
    slug: "palm-collection-pacaembu",
    name: "Palm Collection Pacaembu",
    neighborhood: "Pacaembu",
    city: "São Paulo",
    bedrooms: "3 e 4 suítes",
    area: "248 a 565 m2",
    priceLabel: "Sob consulta",
    developer: "EXTO",
    delivery: "2029",
    status: "lancamento",
    address: "Rua Turiassú, 59 - Pacaembu, São Paulo - SP",
    tourUrl: "https://tour3d.piperz.io/CpWdX9aJPQb",
    specs: [
      { label: "Suítes", value: "3 e 4" },
      { label: "Unidades", value: "42 (exclusivas)" },
      { label: "Arquitetura", value: "Dina Melaragno" },
    ],
    description:
      "Palm Collection Pacaembu é a mais nova peça da coleção exclusiva da EXTO na Zona Oeste, na quadra mais desejada do Pacaembu, entre a Rua Turiassú e a Traipu. Um refúgio urbano de apenas 42 unidades, com projeto assinado por Dina Melaragno, apartamentos de 3 e 4 suítes (248 e 288 m², além de unidades de 490 e 565 m² e uma penthouse de 345 m²) e estrutura de clube privativo.",
    features: [
      "Quadra de tênis (saibro)",
      "Piscina",
      "Fitness",
      "Spa e sauna úmida",
      "Salão de festas",
      "Espaço gourmet",
      "Espaço beauty",
      "Sala de massagem",
      "Brinquedoteca",
      "Playground",
      "Pet place e banho pet",
      "Mini market",
      "Concierge / courrier",
    ],
    images: [
      "/properties/palm-collection-pacaembu/fachada.jpg",
      "/properties/palm-collection-pacaembu/portico.jpg",
      "/properties/palm-collection-pacaembu/portico-2.jpg",
      "/properties/palm-collection-pacaembu/portico-3.jpg",
      "/properties/palm-collection-pacaembu/fachada-2.jpg",
      "/properties/palm-collection-pacaembu/hall-principal.jpg",
      "/properties/palm-collection-pacaembu/hall.jpg",
      "/properties/palm-collection-pacaembu/quadra-de-tenis.jpg",
      "/properties/palm-collection-pacaembu/aerea-quadra-tenis.jpg",
      "/properties/palm-collection-pacaembu/clube-tenis.jpg",
      "/properties/palm-collection-pacaembu/piscina.jpg",
      "/properties/palm-collection-pacaembu/aerea-piscina.jpg",
      "/properties/palm-collection-pacaembu/fitness.jpg",
      "/properties/palm-collection-pacaembu/spa.jpg",
      "/properties/palm-collection-pacaembu/sala-de-massagem.jpg",
      "/properties/palm-collection-pacaembu/espaco-beauty.jpg",
      "/properties/palm-collection-pacaembu/salao-de-festas.jpg",
      "/properties/palm-collection-pacaembu/brinquedoteca.jpg",
      "/properties/palm-collection-pacaembu/espaco-pet.jpg",
    ],
    featured: false,
  },
];
